---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: flux-system
  labels:
    app: uptime-kuma
spec:
  interval: 10m
  timeout: 5m
  targetNamespace: uptime-kuma
  chart:
    spec:
      chart: uptime-kuma
      sourceRef:
        kind: HelmRepository
        name: uptime-kuma
        namespace: flux-system
      interval: 5m0s
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    volume:
      existingClaim: uptime-kuma-pvc