---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - keycloak-ocirepository.yaml
  - keycloak-db-helmrelease.yaml
  - keycloak-pvc.yaml
  - keycloak-helmrelease.yaml
  - keycloak-httproute.yaml
