apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: matrix-ocirepo
  namespace: flux-system
spec:
  interval: 10m
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://ghcr.io/element-hq/ess-helm/matrix-stack
  ref:
    semver: ">= 26.2.4-dev"