---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wekan
  namespace: flux-system
  labels:
    app: wekan
spec:
  interval: 10m
  timeout: 5m
  targetNamespace: wekan
  chart:
    spec:
      chart: wekan
      sourceRef:
        kind: HelmRepository
        name: wekan
        namespace: flux-system
      interval: 5m0s
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      tag: "v8.50"  # v8.45 is broken (Node.js v22 breaks @meteorjs/reify)
    env:
      - name: "MONGO_URL"
        value: "mongodb://wekan-wekan-mongodb:27017/wekan"
    secretEnv:
      - name: "MONGO_URL"
        value: "mongodb://wekan-wekan-mongodb:27017/wekan"
    endpoint: "wekan.vps.kubespaces.cloud"
    root_url: "https://wekan.vps.kubespaces.cloud"
    ingress:
      enabled: false
    sharedDataFolder:
      enabled: true
      path: /data
      accessMode: ReadWriteOnce
      storageClass: local-path
      resources:
        requests:
          storage: 5Gi