---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: outline
  namespace: flux-system
  labels:
    app: outline
spec:
  interval: 10m
  timeout: 5m
  targetNamespace: outline
  chart:
    spec:
      chart: outline
      sourceRef:
        kind: HelmRepository
        name: outline
        namespace: flux-system
      interval: 5m0s
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    redis:
      enabled: true
      architecture: standalone
      master:
        persistence:
          enabled: true
    smtp:
      host: "smtp-relay.gmail.com"
      port: 587
      fromEmail: "outline@kubespaces.io"
      replyEmail: "no-reply@kubespaces.io"
      existingSecret:
          name: "outline-smtp"
          usernameKey: "username"
          passwordKey: "password"
      secure: true
    fileStorage:
      mode: "local"

      local:
        persistence:
          enabled: true
          existingClaim: "outline-pvc"
    externalPostgresql:
      host: "outline-outline-database-cluster-rw"
      database: "outline"
      existingSecret: "outline-outline-database-cluster-app"
      passwordSecretKey: "password"
