apiVersion: apps/v1
kind: Deployment
metadata:
  name: coredns
  namespace: kube-system
spec:
  template:
    metadata:
      annotations:
        tailscale.com/hostname: "coredns"
        tailscale.com/tailnet: "on"
