---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: xwiki
  namespace: flux-system
  labels:
    app: xwiki
spec:
  interval: 10m
  timeout: 5m
  targetNamespace: xwiki
  dependsOn:
    - name: xwiki-database
  chart:
    spec:
      chart: xwiki
      sourceRef:
        kind: HelmRepository
        name: xwiki
        namespace: flux-system
      interval: 5m0s
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    externalDB:
      host: xwiki-xwiki-database-cluster-rw
      database: xwiki
      user: xwiki
      password: ''
      customKeyRef:
        enable: true
        name: xwiki-xwiki-database-cluster-app
        key: password