---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: supabase
  namespace: supabase
spec:
  parentRefs:
    - name: gateway
      namespace: istio-system
      sectionName: http   # listener name on the Gateway
  hostnames:
    - "supabase.vps.kubespaces.cloud"  # Change this to your actual domain
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /auth/v1
      backendRefs:
        - name: supabase-supabase-supabase-auth
          port: 9999
    - matches:
        - path:
            type: PathPrefix
            value: /rest/v1
      backendRefs:
        - name: supabase-supabase-supabase-rest
          port: 3000
    - matches:
        - path:
            type: PathPrefix
            value: /realtime/v1
      backendRefs:
        - name: supabase-supabase-supabase-realtime
          port: 4000
    - matches:
        - path:
            type: PathPrefix
            value: /storage/v1
      backendRefs:
        - name: supabase-supabase-supabase-storage
          port: 5000
    - matches:
        - path:
            type: PathPrefix
            value: /functions/v1
      backendRefs:
        - name: supabase-supabase-supabase-functions
          port: 9000
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: supabase-supabase-supabase-studio
          port: 3000
