---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: backstage
  namespace: flux-system
  labels:
    app: backstage
spec:
  interval: 10m
  timeout: 5m
  targetNamespace: backstage
  dependsOn:
    - name: backstage-database
  chart:
    spec:
      chart: backstage
      sourceRef:
        kind: HelmRepository
        name: backstage
        namespace: flux-system
      interval: 5m0s
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    backstage:
      image:
        registry: ghcr.io
        repository: ams0/backstage
        tag: "1.49.3" # renovate: datasource=docker depName=ghcr.io/ams0/backstage
      appConfig:
        app:
          title: Backstage
          baseUrl: https://backstage.vps.kubespaces.cloud
        backend:
          baseUrl: https://backstage.vps.kubespaces.cloud
          database:
            client: pg
            connection:
              host: backstage-backstage-database-cluster-rw
              port: 5432
              user: backstage
              password: ${POSTGRES_PASSWORD}
        auth:
          session:
            secret: ${SESSION_SECRET}
          environment: development
          providers:
            oidc:
              development:
                metadataUrl: https://auth.vps.kubespaces.cloud/realms/master/.well-known/openid-configuration
                clientId: backstage
                clientSecret: ${OIDC_CLIENT_SECRET}
                prompt: auto
                signIn:
                  resolvers:
                    - resolver: emailMatchingUserEntityProfileEmail
        catalog:
          import:
            entityFilename: catalog-info.yaml
            pullRequestBranchName: backstage-integration
          rules:
            - allow: [Component, System, API, Resource, Location, Group, User]
          locations:
            - type: url
              target: https://raw.githubusercontent.com/ams0/cloudlab/main/gitops/apps/backstage/catalog/all.yaml
              rules:
                - allow: [Location, Component, System, Group, User]
      resources:
        requests:
          cpu: 100m
          memory: 512Mi
        limits:
          cpu: 1500m
          memory: 2Gi
      extraEnvVars:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backstage-backstage-database-cluster-app
              key: password
        - name: OIDC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: backstage-oidc
              key: clientSecret
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: backstage-oidc
              key: sessionSecret
    ingress:
      enabled: false
    postgresql:
      enabled: false
