---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - backstage-helmrepo.yaml
  - backstage-db-helmrelease.yaml
  - backstage-helmrelease.yaml
  - backstage-httproute.yaml