apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: alarik-ocirepo
  namespace: flux-system
spec:
  interval: 10m
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://ghcr.io/ams0/alarik
  ref:
    semver: ">= 0.1.0"
