---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: waha
  namespace: waha
spec:
  replicas: 1
  selector:
    matchLabels:
      app: waha
  template:
    metadata:
      labels:
        app: waha
    spec:
      containers:
        - name: waha
          image: devlikeapro/waha:arm # renovate: datasource=docker depName=devlikeapro/waha
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: waha-data
              mountPath: /app/.sessions
              subPath: sessions
            - name: waha-data
              mountPath: /app/.media
              subPath: media
          resources:
            requests:
              ephemeral-storage: "256Mi"
            limits:
              ephemeral-storage: "512Mi"
      volumes:
        - name: waha-data
          persistentVolumeClaim:
            claimName: waha-pvc
