apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: waha-pvc
  namespace: waha
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
