---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: actual
  namespace: flux-system
  labels:
    app: actual
spec:
  interval: 10m
  timeout: 5m
  targetNamespace: actual
  chart:
    spec:
      chart: actualbudget
      sourceRef:
        kind: HelmRepository
        name: actual
        namespace: flux-system
      interval: 5m0s
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      tag: "26.3.0"
    ingress:
      enabled: false
    persistence:
      enabled: true
      existingClaim: actual-pvc
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 500m
        memory: 512Mi
