---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - keycloak
  - n8n
#  - harbor
  - minecraft
  - stakater
  - garage
  - forgejo
  - dashy
  - rancher
  - actual
  - supabase
  - openclaw
  - authentik
  - openwebui
  - xwiki
  - coder
  - vikunja
  - waha
  - omni
  - tailscale