---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - vikunja-ocirepository.yaml
  - vikunja-db-helmrelease.yaml
  - vikunja-helmrelease.yaml
  - vikunja-httproute.yaml
