---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vikunja
  namespace: flux-system
  labels:
    app: vikunja
spec:
  interval: 10m
  timeout: 5m
  targetNamespace: vikunja
  chartRef:
    kind: OCIRepository
    name: vikunja-ocirepo
    namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    vikunja:
      ingress:
        main:
          enabled: false # set in resources
      env:
        VIKUNJA_SERVICE_PUBLICURL: "https://todo.vps.kubespaces.cloud"
        VIKUNJA_DATABASE_TYPE: "postgres"
        VIKUNJA_DATABASE_USER: "vikunja"
        VIKUNJA_DATABASE_PASSWORD:
          valueFrom:
            secretKeyRef:
              name: vikunja-vikunja-database-cluster-app
              key: password
        VIKUNJA_DATABASE_NAME: vikunja
        VIKUNJA_DATABASE_DATABASE: vikunja
        VIKUNJA_DATABASE_HOST: vikunja-vikunja-database-cluster-rw
        VIKUNJA_DEFAULTSETTINGS_EMAIL_REMINDERS_ENABLED: true
        VIKUNJA_DEFAULTSETTINGS_WEEK_START: 1
        VIKUNJA_DEFAULTSETTINGS_OVERDUE_TASKS_REMINDERS_TIME: 7:00
        VIKUNJA_DEFAULTSETTINGS_DISCOVERABLE_BY_NAME: true
        VIKUNJA_MAILER_ENABLED: true
        VIKUNJA_MAILER_HOST: smtp.gmail.com
        VIKUNJA_MAILER_USERNAME: alessandro@kubespaces.io
        VIKUNJA_MAILER_PASSWORD:
          valueFrom:
            secretKeyRef:
              name: vikunja-smtp
              key: password
        VIKUNJA_MAILER_FROMEMAIL: alessandro@kubespaces.io




