---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - velero-helmrepo.yaml
  - velero-helmrelease.yaml

# DNS patch applied manually via kubectl to avoid kustomization validation errors
# patchesStrategicMerge:
#   - velero-dns-patch.yaml
