---
smb_mounts:
  - name: feynman-velero
    share: "//feynman.rhino-butterfly.ts.net/Store"
    subpath: "Borg/Velero"
    local_path: /mnt/feynman_velero
    username: feynman
    uid: "1001"
    gid: "1001"
