apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- flux-receiver
- gateway-api/experimental-install-v1.4.0.yaml
- istio
- observability
- loki
- cnpg
- databases
- apps
- gateways/configmap.yaml
- gateways/gateway.yaml
- local-path-provisioner/local-path-provisioner.yaml
- argocd
- velero
- system

patchesStrategicMerge:
- system/coredns-tailscale-patch.yaml