{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alarik.fullname" . }}
  labels:
    {{- include "alarik.labels" . | nindent 4 }}
type: Opaque
stringData:
  ADMIN_USERNAME: {{ .Values.auth.adminUsername | quote }}
  ADMIN_PASSWORD: {{ .Values.auth.adminPassword | quote }}
  JWT: {{ .Values.auth.jwtKey | quote }}
  {{- if .Values.auth.defaultAccessKey }}
  DEFAULT_ACCESS_KEY: {{ .Values.auth.defaultAccessKey | quote }}
  {{- end }}
  {{- if .Values.auth.defaultSecretKey }}
  DEFAULT_SECRET_KEY: {{ .Values.auth.defaultSecretKey | quote }}
  {{- end }}
{{- end }}
